---
# Build Docker images using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/rspamd/
# Documentation http://plugins.drone.io/drone-plugins/drone-docker/ is not comprehensive
# Refer to the source: https://github.com/drone-plugins/drone-docker
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

x-default-settings: &default_settings
  username: { from_secret: docker_username }
  password: { from_secret: docker_password }
  purge: false

x-versions:
  alpine: &alpine_version ALPINE_VERSION=3.17.0
  fedora: &fedora_version FEDORA_VERSION=38

steps:
- name: base_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-gcc/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-gcc/Dockerfile ]
    build_args: [ UBUNTU_VERSION=22.04 ]
    repo: rspamd/ci
    tags: [ "ubuntu-gcc" ]

- name: build_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-build/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-build/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-build" ]
  depends_on: [ base_image ]

- name: test_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-test" ]
  depends_on: [ build_image ]

- name: func_test_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test-func/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test-func/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-test-func" ]
  depends_on: [ test_image ]

- name: perl_tidyall_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: perl-tidyall/Dockerfile
    label_schema: [ docker.dockerfile=perl-tidyall/Dockerfile ]
    build_args: [ *alpine_version ]
    repo: rspamd/ci
    tags: [ "perl-tidyall" ]

- name: fedora_build_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-build/Dockerfile
    label_schema: [ docker.dockerfile=fedora-build/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci
    tags: [ "fedora-build" ]

- name: fedora_test_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-test/Dockerfile
    label_schema: [ docker.dockerfile=fedora-test/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci
    tags: [ "fedora-test" ]
  depends_on: [ fedora_build_image ]

- name: centos8_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: centos-8/Dockerfile
    label_schema: [ docker.dockerfile=centos-8/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-8" ]

- name: centos9_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: centos-9/Dockerfile
    label_schema: [ docker.dockerfile=centos-9/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-9" ]

- name: centos7_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: centos-7/Dockerfile
    label_schema: [ docker.dockerfile=centos-7/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-7" ]

- name: ubuntu_jammy_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-jammy/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-jammy/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-jammy" ]
- name: ubuntu_focal_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-focal/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-focal/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-focal" ]
- name: ubuntu_bionic_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-bionic/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-bionic/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-bionic" ]
- name: debian_bullseye_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: debian-bullseye/Dockerfile
    label_schema: [ docker.dockerfile=debian-bullseye/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "debian-bullseye" ]
- name: debian_buster_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: debian-buster/Dockerfile
    label_schema: [ docker.dockerfile=debian-buster/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "debian-buster" ]
- name: debian_bookworm_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: debian-bookworm/Dockerfile
    label_schema: [ docker.dockerfile=debian-bookworm/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "debian-bookworm" ]

- name: fedora37_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-37/Dockerfile
    label_schema: [ docker.dockerfile=fedora-37/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "fedora-37" ]
- name: fedora38_pkg_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-38/Dockerfile
    label_schema: [ docker.dockerfile=fedora-38/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "fedora-38" ]

trigger:
  branch: [ master ]
  event: [push, tag, custom]
---
kind: signature
hmac: 4eb24f3de17613594fe767b784366f695b2560e4c353675dae0ffa7f72345981

...
