name: ci

on: [push, workflow_dispatch]

jobs:
  ubuntu_ci:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "ubuntu-ci"
      platforms: linux/amd64
    permissions:
      packages: write
      contents: read

  fedora_ci:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "fedora-ci"
      platforms: linux/amd64
    permissions:
      packages: write
      contents: read

  perl_tidyall:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "perl-tidyall"
      platforms: linux/amd64
    permissions:
      packages: write
      contents: read

  centos_7:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "centos-7"
    permissions:
      packages: write
      contents: read
 
  centos_8:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "centos-8"
    permissions:
      packages: write
      contents: read

  centos_9:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "centos-9"
    permissions:
      packages: write
      contents: read

  debian_bullseye:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "debian-bullseye"
    permissions:
      packages: write
      contents: read

  debian_bookworm:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "debian-bookworm"
    permissions:
      packages: write
      contents: read

  rbldnsd_build:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "rbldnsd-build"
    permissions:
      packages: write
      contents: read

  ubuntu_jammy:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "ubuntu-jammy"
    permissions:
      packages: write
      contents: read

  ubuntu_noble:
    uses: ./.github/workflows/docker_build.yml
    with:
      name: "ubuntu-noble"
    permissions:
      packages: write
      contents: read
