name: Publish Docker image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      platforms:
        default: linux/amd64,linux/arm64
        type: string

jobs:
  docker_build:
    name: docker_build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
            label: amd64
          - platform: linux/amd64
            runner: ubuntu-22.04-arm
            label: arm64
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.name }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.name }}-${{ matrix.label }}

  docker_manifest:
    name: docker_manifest
    runs-on: ubuntu-22.04
    needs: docker_build
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Create and push Docker manifest
        uses: docker/manifest-tool@v2
        with:
          manifest_list: ghcr.io/${{ github.repository }}:${{ inputs.name }}
          images: |
            ghcr.io/${{ github.repository }}:${{ inputs.name }}-amd64
            ghcr.io/${{ github.repository }}:${{ inputs.name }}-arm64
