name: Publish Docker image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  docker_build:
    name: docker_build
    runs-on: ["ubuntu-latest"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.name }}
